export const services = [
  {
    service_name: "BuyBacks",
    service_desc: "This is a Buybacks service",
    service_image: "/buyBacks.png",
    service_type: "general_service",
  },
  {
    service_name: "Cleaning",
    service_desc: "This is a cleaning service",
    service_image: "/cleaning.png",
    service_type: "general_service",
  },
  {
    service_name: "Customization",
    service_desc: "This is a Customization service",
    service_image: "/customization.png",
    service_type: "general_service",
  },
  {
    service_name: "Diagnostics",
    service_desc: "This is a Diagnostics service",
    service_image: "/Diagnostics.png",
    service_type: "general_service",
  },
  {
    service_name: "Software",
    service_desc: "This is a software service",
    service_image: "/software.png",
    service_type: "general_service",
  },
  {
    service_name: "Software",
    service_desc: "This is a software service",
    service_image: "/software.png",
    service_type: "general_service",
  },
  {
    service_name: "Unlocks",
    service_desc: "This is a Unlocks service",
    service_image: "/Unlocks.png",
    service_type: "general_service",
  },
  {
    service_name: "Repairs",
    service_desc: "This is a Repairs service",
    service_image: "/repairs.png",
    service_type: "repairs_service",
  },
];

export const brands = [
  {
    brand_name: "Apple",
    brand_image: "/apple_logo.png",
    brand_desc: "Apple products",
  },
  {
    brand_name: "Samsung",
    brand_image: "/samsung_logo.png",
    brand_desc: "Samsung products",
  },
  {
    brand_name: "Microsoft",
    brand_image: "/microsoft_logo.png",
    brand_desc: "Microsoft products",
  },
  {
    brand_name: "Google",
    brand_image: "/google_logo.png",
    brand_desc: "Google products",
  },
  {
    brand_name: "Oneplus",
    brand_image: "/oneplus_logo.png",
    brand_desc: "Oneplus products",
  },
  {
    brand_name: "LG",
    brand_image: "/lg_logo.png",
    brand_desc: "LG products",
  },
  {
    brand_name: "Sony",
    brand_image: "/sony_logo.png",
    brand_desc: "Sony products",
  },
  {
    brand_name: "Nintendo",
    brand_image: "/nintendo_logo.png",
    brand_desc: "Nintendo products",
  },
  {
    brand_name: "Motorola",
    brand_image: "/motorola_logo.png",
    brand_desc: "Motorola products",
  },
];

export const categories = [
  {
    type_Of_Repair: "Buybacks",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 1,
  },
  {
    type_Of_Repair: "Trade-Ins",
    raw: 80,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 180,
    service_id: 1,
  },
  {
    type_Of_Repair: "Laptobs",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 2,
  },
  {
    type_Of_Repair: "Phones",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 2,
  },
  {
    type_Of_Repair: "Computers",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 2,
  },
  {
    type_Of_Repair: "Consoles",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 2,
  },
  {
    type_Of_Repair: "Watches",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 2,
  },
  {
    type_Of_Repair: "Phones Custom Cases",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "120 mins",
    total: 450,
    service_id: 3,
  },
  {
    type_Of_Repair: "Phones Custom Skins",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "120 mins",
    total: 450,
    service_id: 3,
  },
  {
    type_Of_Repair: "Laptobs",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 4,
  },
  {
    type_Of_Repair: "Phones",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 4,
  },
  {
    type_Of_Repair: "Computers",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 4,
  },
  {
    type_Of_Repair: "Consoles",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 4,
  },
  {
    type_Of_Repair: "Watches",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "20 mins",
    total: 450,
    service_id: 4,
  },
  {
    type_Of_Repair: "Recovery",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "60 mins",
    total: 450,
    service_id: 5,
  },
  {
    type_Of_Repair: "Data Transfer",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "60 mins",
    total: 450,
    service_id: 5,
  },
  {
    type_Of_Repair: "Operating Systems",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "60 mins",
    total: 450,
    service_id: 5,
  },
  {
    type_Of_Repair: "Troubleshooting",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "60 mins",
    total: 450,
    service_id: 5,
  },
  {
    type_Of_Repair: "Virus and Malware Removal",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "60 mins",
    total: 450,
    service_id: 5,
  },
  {
    type_Of_Repair: "Carrier",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "120 mins",
    total: 450,
    service_id: 6,
  },
  {
    type_Of_Repair: "Passcode",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "120 mins",
    total: 450,
    service_id: 6,
  },
];

export const series = [
  {
    series_name: "Iphone",
    series_image: "/iphone_image.png",
    series_desc: "Apple iPhone series",
    brand_id: 1,
  },
  {
    series_name: "Ipad",
    series_image: "/ipad_image.png",
    series_desc: "Apple iPad series",
    brand_id: 1,
  },
  {
    series_name: "Watch",
    series_image: "/watch_image.png",
    series_desc: "Apple Watch series",
    brand_id: 1,
  },
  {
    series_name: "MacBook",
    series_image: "/macbook_image.png",
    series_desc: "Apple MacBook series",
    brand_id: 1,
  },
  {
    series_name: "Galaxy S",
    series_image: "/galaxy_s_image.png",
    series_desc: "Samsung Galaxy S series",
    brand_id: 2,
  },
  {
    series_name: "Galaxy Note",
    series_image: "/galaxy_note_image.png",
    series_desc: "Samsung Galaxy Note series",
    brand_id: 2,
  },
  {
    series_name: "A series",
    series_image: "/a_series_image.png",
    series_desc: "Samsung Galaxy A series",
    brand_id: 2,
  },
  {
    series_name: "Pixel",
    series_image: "/pixel_image.png",
    series_desc: "Google Pixel series",
    brand_id: 3,
  },
  {
    series_name: "Surface Pro",
    series_image: "/surface_pro_image.png",
    series_desc: "Microsoft Surface Pro series",
    brand_id: 4,
  },
  {
    series_name: "Surface Book",
    series_image: "/surface_book_image.png",
    series_desc: "Microsoft Surface Book series",
    brand_id: 4,
  },
  {
    series_name: "Xbox",
    series_image: "/xbox_image.png",
    series_desc: "Microsoft Xbox series",
    brand_id: 4,
  },
  {
    series_name: "Phones",
    series_image: "/generic_phone_image.png",
    series_desc: "Generic Phones series",
    brand_id: 5,
  },
  {
    series_name: "LG phones",
    series_image: "/lg_phone_image.png",
    series_desc: "LG Phones series",
    brand_id: 6,
  },
  {
    series_name: "Consoles",
    series_image: "/consoles_image.png",
    series_desc: "Gaming Consoles series",
    brand_id: 7,
  },
  {
    series_name: "Nintendo",
    series_image: "/nintendo_image.png",
    series_desc: "Nintendo Consoles series",
    brand_id: 8,
  },
  {
    series_name: "Motorola",
    series_image: "/motorola_image.png",
    series_desc: "Motorola Phones series",
    brand_id: 9,
  },
];

export const model = [
  {
    model_name: "iPhone 15 Pro Max",
    model_image: "/iphone15_pro_max_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 15 Pro",
    model_image: "/iphone15_pro_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 15 Plus",
    model_image: "/iphone15_plus_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 15",
    model_image: "/iphone15_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 14 Pro Max",
    model_image: "/iphone14_pro_max_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 14 Pro",
    model_image: "/iphone14_pro_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 14 Plus",
    model_image: "/iphone14_plus_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 14",
    model_image: "/iphone14_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone SE 2022",
    model_image: "/iphone_se_2022_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 13 Pro Max",
    model_image: "/iphone13_pro_max_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 13 Pro",
    model_image: "/iphone13_pro_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 13",
    model_image: "/iphone13_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 13 Mini",
    model_image: "/iphone13_mini_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 12 Pro Max",
    model_image: "/iphone12_pro_max_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 12 Pro",
    model_image: "/iphone12_pro_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 12",
    model_image: "/iphone12_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 12 Mini",
    model_image: "/iphone12_mini_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 11 Pro Max",
    model_image: "/iphone11_pro_max_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 11 Pro",
    model_image: "/iphone11_pro_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 11",
    model_image: "/iphone11_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone XS Max",
    model_image: "/iphone_xs_max_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone XS",
    model_image: "/iphone_xs_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone XR",
    model_image: "/iphone_xr_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone X",
    model_image: "/iphone_x_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 8 Plus",
    model_image: "/iphone8_plus_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 8",
    model_image: "/iphone8_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone SE 2020",
    model_image: "/iphone_se_2020_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 7 Plus",
    model_image: "/iphone7_plus_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 7",
    model_image: "/iphone7_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 6s Plus",
    model_image: "/iphone6s_plus_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 6s",
    model_image: "/iphone6s_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 6 Plus",
    model_image: "/iphone6_plus_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 6",
    model_image: "/iphone6_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 5 SE",
    model_image: "/iphone5_se_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 5C",
    model_image: "/iphone5c_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 5S",
    model_image: "/iphone5s_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 5",
    model_image: "/iphone5_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 4S",
    model_image: "/iphone4s_image.png",
    series_id: 1,
  },
  {
    model_name: "iPhone 4",
    model_image: "/iphone4_image.png",
    series_id: 1,
  },
  {
    model_name: "iPad Pro 12.9",
    model_image: "/ipad_pro_12_9_image.png",
    series_id: 2,
  },
  {
    model_name: "iPad Pro 11",
    model_image: "/ipad_pro_11_image.png",
    series_id: 2,
  },
  {
    model_name: "iPad Pro 10.5",
    model_image: "/ipad_pro_10_5_image.png",
    series_id: 2,
  },
  {
    model_name: "iPad Pro 9.7",
    model_image: "/ipad_pro_9_7_image.png",
    series_id: 2,
  },
  {
    model_name: "Galaxy S24",
    model_image: "/galaxy_s24_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S23",
    model_image: "/galaxy_s23_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S22",
    model_image: "/galaxy_s22_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S21",
    model_image: "/galaxy_s21_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S20",
    model_image: "/galaxy_s20_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S10",
    model_image: "/galaxy_s10_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S9",
    model_image: "/galaxy_s9_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S8",
    model_image: "/galaxy_s8_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S7",
    model_image: "/galaxy_s7_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S6",
    model_image: "/galaxy_s6_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S5",
    model_image: "/galaxy_s5_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S4",
    model_image: "/galaxy_s4_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy S3",
    model_image: "/galaxy_s3_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 20",
    model_image: "/galaxy_note_20_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 10",
    model_image: "/galaxy_note_10_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 9",
    model_image: "/galaxy_note_9_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 8",
    model_image: "/galaxy_note_8_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 7",
    model_image: "/galaxy_note_7_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 5",
    model_image: "/galaxy_note_5_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 4",
    model_image: "/galaxy_note_4_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 3",
    model_image: "/galaxy_note_3_image.png",
    series_id: 3,
  },
  {
    model_name: "Galaxy Note 2",
    model_image: "/galaxy_note_2_image.png",
    series_id: 3,
  },
  {
    model_name: "Pixel 8 Pro",
    model_image: "/pixel_8_pro_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 8",
    model_image: "/pixel_8_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 7 Pro",
    model_image: "/pixel_7_pro_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 7",
    model_image: "/pixel_7_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 6 Pro",
    model_image: "/pixel_6_pro_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 6",
    model_image: "/pixel_6_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 5a",
    model_image: "/pixel_5a_image.png",
    series_id: 4,
  },
  {
    model_name: "Pixel 5",
    model_image: "/pixel_5_image.png",
    series_id: 4,
  },
  {
    model_name: "Surface Pro 7 Plus",
    model_image: "/surface_pro_7_plus_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Pro 7",
    model_image: "/surface_pro_7_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Pro 6",
    model_image: "/surface_pro_6_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Pro 5",
    model_image: "/surface_pro_5_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Pro 4",
    model_image: "/surface_pro_4_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Pro 3",
    model_image: "/surface_pro_3_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Book 2",
    model_image: "/surface_book_2_image.png",
    series_id: 5,
  },
  {
    model_name: "Surface Book 1",
    model_image: "/surface_book_1_image.png",
    series_id: 5,
  },
  {
    model_name: "Xbox Series X",
    model_image: "/xbox_series_x_image.png",
    series_id: 5,
  },
  {
    model_name: "Xbox Series S",
    model_image: "/xbox_series_s_image.png",
    series_id: 5,
  },
  {
    model_name: "Xbox One X",
    model_image: "/xbox_one_x_image.png",
    series_id: 5,
  },
  {
    model_name: "Xbox One S",
    model_image: "/xbox_one_s_image.png",
    series_id: 5,
  },
  {
    model_name: "Xbox One",
    model_image: "/xbox_one_image.png",
    series_id: 5,
  },
];

export const modelCategory = [
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 1,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 2,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 3,
  },

  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 4,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 5,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 6,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 7,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 8,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 9,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 10,
  },

  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 11,
  },

  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 12,
  },

  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 13,
  },

  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 14,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 15,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 16,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 17,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 18,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 19,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 20,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 21,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 22,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 23,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 24,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 25,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 26,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 27,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 28,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 29,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 30,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 31,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 32,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 33,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 34,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 35,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 36,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 37,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 38,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 39,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 40,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 41,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 42,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 43,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 44,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 45,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 46,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 47,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 48,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 49,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 50,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 51,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 52,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 53,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 54,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 55,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 56,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 57,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 58,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 59,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 60,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 61,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 62,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 63,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 64,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 65,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 66,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 67,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 68,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 69,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 70,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 71,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 72,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 73,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 74,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 75,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 76,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 77,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 78,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 79,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 80,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 81,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 82,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 83,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 84,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 85,
  },
  {
    type_of_repair: "Screen Replacement",
    raw: 200,
    tax: 10.25,
    shipping: 5,
    timeFrame: "30 mins",
    total: 450,
    model_id: 86,
  },
];
